version: "2"

services:

  vuetify:
    build: "./vuetify"
    environment:
      - VUE_APP_API_SERVER
      - VUE_APP_I18N_LOCALE
      - VUE_APP_I18N_FALLBACK_LOCALE
    volumes:
      # - "./vuetify/src:/vuetify/src"
      # - "static_files:/vuetify/dist"
      - "./dist:/vuetify/dist"

  # nginx:
  #   build: "./nginx"
  #   ports:
  #     - "${HTTPD_PORT}:80"
  #   volumes:
  #     - "static_files:/usr/share/nginx/html"
  #     - "upload_files:/usr/share/nginx/html/uploads"

volumes:
  static_files: {}
  # db_files: {}
  # upload_files: {}
